version: "3"

x-restart-policy:
  &restart-policy
  restart: unless-stopped

services:
  bot:
    <<: *restart-policy
    depends_on:
      - postgres
    build: .
    pull_policy: build
    volumes:
      - ./logs:/bot/logs
    environment:
      TOKEN: ${TOKEN:?Your Discord bot TOKEN is required}
      DB_URI: postgresql://postgres:postgres@postgres:5432/bot
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      DEBUG_GUILD_ID: ${DEBUG_GUILD_ID:?Your testing Discord DEBUG_GUILD_ID is required}
      LOG_CHANNEL_ID: ${LOG_CHANNEL_ID:?Your testing Discord LOG_CHANNEL_ID is required}
  postgres:
    <<: *restart-policy
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PG_VOLUME:-./pg_data}:/var/lib/postgresql/data
